# Konfigurasi dasar untuk Netlify
[build]
  # Direktori tempat Netlify akan menemukan fungsi serverless Anda.
  # Pastikan direktori ini ada di root proyek Anda.
  functions = "netlify/functions"
